spring:
  profiles:
    active: dev

  app:
    security:
      protectUrl: /api/**
      permitUrl: /api/auth/login,/api/auth/register
      tokenExpirationTime: 1800
      refreshTokenExpTime: 3600
      tokenSigningKey: ebor123
      tokenHeaderParam: X-Authorization


---
spring:
  profiles: dev
server:
  port: 8088
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "debug"


---
spring:
  profiles: test
server:
  port: 10010
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "debug"


---
spring:
  profiles: prd
server:
  port: 80
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "info"
