spring:
  profiles:
    active: dev
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ebor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
      username: root
      password: root1234
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20



  app:
    security:
      protectUrl: /api/**
      permitUrl: /api/auth/login,/api/auth/register
      tokenExpirationTime: 1800
      refreshTokenExpTime: 3600
      tokenSigningKey: ebor123
      tokenHeaderParam: X-Authorization


---
spring:
  profiles: dev
server:
  port: 8088
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "debug"


---
spring:
  profiles: test
server:
  port: 10010
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "debug"


---
spring:
  profiles: prd
server:
  port: 80
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "info"
