spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 8088
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "debug"


---
spring:
  profiles: test
server:
  port: 10010
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "debug"


---
spring:
  profiles: prd
server:
  port: 80
ebor:
  log:
    path: "/Users/yinjunwu/dev-work/logs/ebor"
    level: "info"
